name: Build and push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Log in to GitHub container registry
#         run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u $ --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/hmedney/schema-tools:latest
      - name: Push
        run: docker push ghcr.io/hmedney/schema-tools:latest
